channels:
- conda-forge
dependencies:
- python=3.10.17
- pip<=23.3.1
- pip:
  - mlflow==2.8.1
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - packaging==23.2
  - psutil==7.0.0
  - pyyaml==6.0.2
  - scikit-learn==1.4.1.post1
  - scipy==1.15.2
name: mlflow-env
